#!/usr/bin/env bash
# Extract the per-species pixel grids from gitagotchi-species-gallery.html —
# the gallery's embedded `states` object is the drawn truth, so the terminal
# renders exactly those grids (recolored per user language at draw time).
# Sibling of extract-palettes.sh; run both when the gallery is redrawn.
# usage: tools/extract-sprites.sh <gallery.html> [out=sprites/sprites-pixel.txt]
#
# --anamorphic squeezes a 48×36 gallery to the 48×18 the quadrant renderer
# wants (lib/pixel.sh PIX_PACK): 24 cols × 9 rows — the original footprint at
# double the pixels. It merges row pairs, letting detail letters (eyes, accent,
# blush) win over body fill so thin features survive. That is a MECHANICAL
# squeeze, not a redraw: it halves vertical resolution. Draw the gallery at
# 48×18 natively and run without the flag to keep every pixel you drew.
set -euo pipefail
ANAMORPHIC=0
[[ ${1:-} == --anamorphic ]] && { ANAMORPHIC=1; shift; }
GALLERY=${1:?usage: extract-sprites.sh [--anamorphic] <gallery.html> [out]}
OUT=${2:-"$(dirname "$0")/../sprites/sprites-pixel.txt"}

# Same one-physical-line assumption as extract-palettes.sh: if the gallery is
# ever reformatted, sed matches nothing and jq on empty input exits 0 with no
# output — which would silently truncate the sprite file. Assert at each stage
# so a format drift fails loudly instead.
species=$(sed -n 's/^const SPECIES = \(.*\);$/\1/p' "$GALLERY")
[[ -n $species ]] || { echo "error: no single-line 'const SPECIES = [...];' found in $GALLERY" >&2; exit 1; }

# states holds the 13 animation frames as <state> → [grid, …]; f1/f2 are just
# aliases of states.idle and are ignored. Frame names are <state>_<1-based>,
# which is the vocabulary lib/pixel.sh already loads.
grids=$(jq -r '
  ["idle","sleep","eat","sick","celebrate","hibernate"] as $order
  | .[]
  | . as $s
  | "### \($s.id)  (\($s.name) · linguist \($s.lang) \($s.hex))",
    ( $order[] as $st
      | range(0; ($s.states[$st] | length)) as $i
      | ":frame \($st)_\($i + 1)", ($s.states[$st][$i][]) ),
    ""
' <<<"$species")
[[ -n $grids ]] || { echo "error: parsed 0 sprites from $GALLERY" >&2; exit 1; }

if (( ANAMORPHIC )); then
  # merge each row pair: a detail letter beats body fill, and paint beats
  # transparency, so eyes and outlines survive the squeeze instead of
  # dropping out on whichever row happened to be even.
  grids=$(awk '
    function pick(a, b,   i, out, p, q) {
      out = ""
      for (i = 1; i <= length(a); i++) {
        p = substr(a, i, 1); q = substr(b, i, 1)
        if (p == q)                 out = out p
        else if (p ~ /[KWPR]/)      out = out p
        else if (q ~ /[KWPR]/)      out = out q
        else if (p == ".")          out = out q
        else                        out = out p
      }
      return out
    }
    /^[.A-Z]+$/ { if (held == "") { held = $0 } else { print pick(held, $0); held = "" } ; next }
    { if (held != "") { print held; held = "" } ; print }
  ' <<<"$grids")
  [[ -n $grids ]] || { echo "error: anamorphic squeeze produced nothing" >&2; exit 1; }
fi

n_species=$(grep -c '^### ' <<<"$grids")
n_frames=$(grep -c '^:frame ' <<<"$grids")
(( n_species > 0 && n_frames > 0 )) || { echo "error: no species/frames emitted" >&2; exit 1; }

# every grid row must be the same width, and the file's header advertises that
# width — a ragged grid would desync the half-block pairing silently
dims=$(grep -E '^[.A-Z]+$' <<<"$grids" | awk '{print length}' | sort -un)
[[ $(wc -l <<<"$dims") -eq 1 ]] || { echo "error: ragged grids, widths: $(tr '\n' ' ' <<<"$dims")" >&2; exit 1; }
w=$dims
rows=$(grep -cE '^[.A-Z]+$' <<<"$grids")
h=$(( rows / n_frames ))
(( rows % n_frames == 0 )) || { echo "error: $rows rows over $n_frames frames is not a whole grid height" >&2; exit 1; }

{
  printf '# gitagotchi pixel sprites · %s species · %sx%s palette-indexed grids\n' "$n_species" "$w" "$h"
  printf '# letters: O body · D outline · W light · K eyes/dark · P accent · R blush · S shade\n'
  printf '# body palette derives from linguist color; blink = eye rows K->D (derived)\n'
  printf '# GENERATED by tools/extract-sprites.sh — edit the gallery, not this file\n\n'
  printf '%s\n' "$grids"
} > "$OUT"

echo "wrote $OUT — $n_species species · $n_frames frames · ${w}x${h}"
